#                                DATA ANALYSIS MID PROJECT

In [60]:
import pandas as pd
import numpy as np
import plotly.express as px

## step 1: Load the data

In [169]:
df_adverse_events = pd.read_csv('adverse_events.csv')
df_drugs = pd.read_csv("drugs_overview.csv")
df_prices = pd.read_csv("stock_prices.csv")
df_adverse_events.head()

,safetyreportid,generic_name,brand_queried,receive_date,country,serious,seriousness_death,seriousness_lifethreatening,seriousness_hospitalization,seriousness_disabling,patient_age,patient_age_unit,patient_sex,patient_weight_kg,reaction,reaction_outcome
0,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Stenosis,Unknown
1,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Hunger,Unknown
2,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Visual impairment,Unknown
3,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Incorrect dose administered,Unknown
4,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Inappropriate schedule of product administration,Unknown

In [170]:
# to load drugs overview data

df = df_adverse_events.merge(df_drugs, on="generic_name", how="left")
df.head()

,safetyreportid,generic_name,brand_queried,receive_date,country,serious,seriousness_death,seriousness_lifethreatening,seriousness_hospitalization,seriousness_disabling,patient_age,patient_age_unit,patient_sex,patient_weight_kg,reaction,reaction_outcome,brand_names,manufacturer,indication,fda_first_approval_date,is_investigational,drug_class
0,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Stenosis,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,False,GLP-1 receptor agonist
1,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Hunger,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,False,GLP-1 receptor agonist
2,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Visual impairment,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,False,GLP-1 receptor agonist
3,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Incorrect dose administered,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,False,GLP-1 receptor agonist
4,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Inappropriate schedule of product administration,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,False,GLP-1 receptor agonist

In [171]:
# to show all columns in the dataframe

pd.set_option('display.max_columns', None)

## step 2 : Data description / understanding

| Column Name | Description |
|---|---|
| `safetyreportid` | Unique identifier for the safety report. |
| `generic_name` | Generic name of the reported drug. |
| `brand_queried` | Brand name associated with the reported drug. |
| `receive_date` | Date when the adverse-event report was received. |
| `country` | Country associated with the adverse-event report. |
| `serious` | Indicates whether the reported event was classified as serious. |
| `seriousness_death` | Indicates whether the event resulted in death. |
| `seriousness_lifethreatening` | Indicates whether the event was considered life-threatening. |
| `seriousness_hospitalization` | Indicates whether the event resulted in or required hospitalization. |
| `seriousness_disabling` | Indicates whether the event resulted in disability or incapacity. |
| `patient_age` | Age of the patient at the time of the report. |
| `patient_age_unit` | Unit used to report the patient's age. |
| `patient_sex` | Sex of the patient. |
| `patient_weight_kg` | Patient body weight in kilograms. |
| `reaction` | Reported adverse reaction or event. |
| `reaction_outcome` | Outcome of the reported reaction. |
| `brand_names` | Brand names associated with the drug. |
| `manufacturer` | Pharmaceutical company that manufactures or develops the drug. |
| `indication` | Medical condition(s) or purpose(s) for which the drug is used or investigated. |
| `fda_first_approval_date` | Date when the drug first received FDA approval. |
| `is_investigational` | Indicates whether the drug is investigational rather than approved. |
| `drug_class` | Pharmacological class or type of the drug. |

## step 3 : Data Exploration

In [64]:
# check data types

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149209 entries, 0 to 149208
Data columns (total 22 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   safetyreportid               149209 non-null  int64
 1   generic_name                 149209 non-null  str
 2   brand_queried                149209 non-null  str
 3   receive_date                 149209 non-null  str
 4   country                      149209 non-null  str
 5   serious                      149209 non-null  bool
 6   seriousness_death            149209 non-null  bool
 7   seriousness_lifethreatening  149209 non-null  bool
 8   seriousness_hospitalization  149209 non-null  bool
 9   seriousness_disabling        149209 non-null  bool
 10  patient_age                  94392 non-null   float64
 11  patient_age_unit             149209 non-null  str
 12  patient_sex                  149209 non-null  str
 13  patient_weight_kg            44716 non-null   float64
 14  reaction                     149209 non-null  str
 15  reaction_outcome             149209 non-null  str
 16  brand_names                  149209 non-null  str
 17  manufacturer                 149209 non-null  str
 18  indication                   149209 non-null  str
 19  fda_first_approval_date      149209 non-null  str
 20  is_investigational           149209 non-null  bool
 21  drug_class                   149209 non-null  str
dtypes: bool(6), float64(2), int64(1), str(13)
memory usage: 19.1 MB

In [65]:
# Check duplicates

print(df.duplicated().sum())

0

In [66]:
# Check summary statistics for Numerical columns

df.describe().round(2)

       safetyreportid  patient_age  patient_weight_kg
count       149209.00     94392.00           44716.00
mean      16084752.11        56.44             107.97
std        5039507.69        13.06            1007.79
min       10005908.00         0.00               1.70
25%       11405367.00        48.00              79.40
50%       14893477.00        57.60              93.96
75%       21374595.00        66.00             109.00
max       24857834.00       100.00           87075.00

In [67]:
# Check summary statistics for Categorical columns

df.describe(include= ['string']).round(2)

,generic_name,brand_queried,receive_date,country,patient_age_unit,patient_sex,reaction,reaction_outcome,brand_names,manufacturer,indication,fda_first_approval_date,drug_class
count,149209,149209,149209,149209,149209,149209,149209,149209,149209,149209,149209,149209,149209
unique,7,12,2947,73,3,3,4604,6,7,5,2,7,3
top,semaglutide,BYETTA,2014-05-10,US,Year,Female,Nausea,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,GLP-1 receptor agonist
freq,45818,17383,4239,126927,94397,97614,7629,90845,45818,72265,94121,45818,114517

In [68]:
# Check for missing values

df.isna().mean().round(4) * 100

safetyreportid                  0.00
generic_name                    0.00
brand_queried                   0.00
receive_date                    0.00
country                         0.00
serious                         0.00
seriousness_death               0.00
seriousness_lifethreatening     0.00
seriousness_hospitalization     0.00
seriousness_disabling           0.00
patient_age                    36.74
patient_age_unit                0.00
patient_sex                     0.00
patient_weight_kg              70.03
reaction                        0.00
reaction_outcome                0.00
brand_names                     0.00
manufacturer                    0.00
indication                      0.00
fda_first_approval_date         0.00
is_investigational              0.00
drug_class                      0.00
dtype: float64

## step 4 : Data cleaning

In [69]:
df.columns

Index(['safetyreportid', 'generic_name', 'brand_queried', 'receive_date',
       'country', 'serious', 'seriousness_death',
       'seriousness_lifethreatening', 'seriousness_hospitalization',
       'seriousness_disabling', 'patient_age', 'patient_age_unit',
       'patient_sex', 'patient_weight_kg', 'reaction', 'reaction_outcome',
       'brand_names', 'manufacturer', 'indication', 'fda_first_approval_date',
       'is_investigational', 'drug_class'],
      dtype='str')

In [73]:
# 1)Check if the saftyreportid is unique or not

print(df['safetyreportid'].nunique())
print(len(df))

54170
149209

### Note: So the length of the data is not the same as the safetyreport that means that i have duplicated report with same patient but multiple adverse reaction.

In [77]:
# Step 1 — Check whether age, weight, and gender are consistent
print(df.groupby("safetyreportid")["patient_age"].nunique(dropna=True).max())
print(df.groupby("safetyreportid")["patient_weight_kg"].nunique(dropna=True).max())
print(df.groupby("safetyreportid")["patient_sex"].nunique(dropna=True).max())

1
1
1

#### conclusion: No safety report contains more than one different recorded age, weight or gender

#### Step 2 — Create a new grouped df for age, weight, and gender for analysis and clean it

#### a) Age

In [172]:
df_age = (
    df.groupby("safetyreportid", as_index=False)["patient_age"]
      .first())
df_age

       safetyreportid  patient_age
0            10005908         52.0
1            10006249         66.0
2            10006256         84.0
3            10006258          NaN
4            10006261         71.0
...               ...          ...
54165        24848430          NaN
54166        24852275         51.0
54167        24853716         70.0
54168        24853808         53.0
54169        24857834          NaN

[54170 rows x 2 columns]

In [173]:
df[df["safetyreportid"] == missing_age_reports.iloc[0]][
    ["safetyreportid", "patient_age", "patient_weight_kg", "patient_sex", "reaction"]
]

,safetyreportid,patient_age,patient_weight_kg,patient_sex,reaction
67679,10006258,NaN,NaN,Male,Pancreatic carcinoma

#### Check among the reports that are NaN in df_age, does ANY of them actually have an age somewhere in the original df?

In [174]:
df[
    df["safetyreportid"].isin(missing_age_reports)
]["patient_age"].notna().sum()

np.int64(0)

In [175]:
px.histogram(df_age, x="patient_age", nbins=20, title="Distribution of Patient Age", labels={"patient_age": "Patient Age"}, color_discrete_sequence=["#636EFA"])

In [176]:
px.box(df_age, y="patient_age", title="Box Plot of Patient Age", labels={"patient_age": "Patient Age"}, color_discrete_sequence=["#636EFA"])

In [177]:
print("Before grouping:")
print(df["patient_age"].isna().mean().round(4) * 100)

print("After grouping:")
print(df_age["patient_age"].isna().mean().round(4) * 100)

Before grouping:
36.74
After grouping:
42.79

In [129]:
from sklearn.impute import KNNImputer

knn = KNNImputer(n_neighbors= 10)

df_age[["patient_age"]] = knn.fit_transform(df_age[["patient_age"]])

In [131]:
px.histogram(df_age, x="patient_age", title="Distribution of Patient Age by Age Unit", nbins=50)

#### b) Weight

In [178]:
df_weight = (
    df.groupby("safetyreportid", as_index=False)["patient_weight_kg"]
      .first())
df_weight

       safetyreportid  patient_weight_kg
0            10005908             118.00
1            10006249              69.39
2            10006256                NaN
3            10006258                NaN
4            10006261             148.75
...               ...                ...
54165        24848430                NaN
54166        24852275                NaN
54167        24853716             113.00
54168        24853808             220.00
54169        24857834                NaN

[54170 rows x 2 columns]

In [179]:
df_age["patient_age"].isna().mean() * 100

np.float64(42.78752076795274)

In [180]:
missing_weight_reports = df_weight[
    df_weight["patient_weight_kg"].isna()
]["safetyreportid"]

missing_weight_reports

2        10006256
3        10006258
6        10006268
7        10006271
8        10006277
           ...
54161    24842670
54162    24843181
54165    24848430
54166    24852275
54169    24857834
Name: safetyreportid, Length: 43987, dtype: int64

In [181]:
df[df["safetyreportid"] == missing_weight_reports.iloc[0]][
    ["safetyreportid", "patient_age", "patient_weight_kg", "patient_sex", "reaction"]
]

,safetyreportid,patient_age,patient_weight_kg,patient_sex,reaction
67678,10006256,84.0,NaN,Female,Adenocarcinoma pancreas

In [182]:
df[
    df["safetyreportid"].isin(missing_weight_reports)
]["patient_weight_kg"].notna().sum()

np.int64(0)

In [183]:
print("Before grouping:")
print(df["patient_weight_kg"].isna().mean().round(4) * 100)

print("After grouping:")
print(df_weight["patient_weight_kg"].isna().mean().round(4) * 100)

Before grouping:
70.03
After grouping:
81.2

In [184]:
df.drop(columns=['patient_weight_kg'], inplace=True)

#### 3) Gender

In [185]:
df["patient_sex"].value_counts(normalize=True, dropna=False).round(4) * 100

patient_sex
Female     65.42
Male       30.32
Unknown     4.26
Name: proportion, dtype: float64

In [186]:
df_gender = df[["safetyreportid", "patient_sex"]].copy()

df_gender["patient_sex"] = df_gender["patient_sex"].replace("Unknown", np.nan)

df_gender = (
    df_gender.groupby("safetyreportid", as_index=False)["patient_sex"]
    .first())

df_gender

       safetyreportid patient_sex
0            10005908      Female
1            10006249        Male
2            10006256      Female
3            10006258        Male
4            10006261        Male
...               ...         ...
54165        24848430         NaN
54166        24852275      Female
54167        24853716        Male
54168        24853808      Female
54169        24857834         NaN

[54170 rows x 2 columns]

In [187]:
print("Before grouping:")
print(df["patient_sex"].isna().mean().round(4) * 100)

print("After grouping:")
print(df_gender["patient_sex"].isna().mean().round(4) * 100)

Before grouping:
0.0
After grouping:
5.96

In [201]:
# Drop rows with missing values in the patient_sex column
df_gender = df_gender.dropna(subset=["patient_sex"]).copy()

In [203]:
df_gender["patient_sex"].value_counts(dropna=False)

patient_sex
Female    34367
Male      16574
Name: count, dtype: int64

In [189]:
#step3 : Change the date to datetime format for the following columns: "receive_date", "fda_first_approva_date"

df["receive_date"] = pd.to_datetime(df["receive_date"])
df["fda_first_approval_date"] = pd.to_datetime(df["fda_first_approval_date"])

df[["receive_date", "fda_first_approval_date"]].dtypes

receive_date               datetime64[us]
fda_first_approval_date    datetime64[us]
dtype: object

## step 4 : Function Engineering

#### The is_investigational variable was evaluated for feature engineering; however, all adverse-event records corresponded to approved drugs (False). Therefore, an approval-status feature was not created because it would have no variability and would not contribute to the analysis.

In [190]:
df["is_investigational"].value_counts(dropna=False)

is_investigational
False    149209
Name: count, dtype: int64

In [191]:
# 1-drop the "is_investigational" column from the dataframe
df.drop(columns=["is_investigational"], inplace=True)

In [192]:
# 2-Extract the year from the "fda_first_approval_date" column

df["approval_year"] = df["fda_first_approval_date"].dt.year

df["approval_year"].unique()

array([2017, 2022, 2010, 2014, 2005, 2016], dtype=int32)

In [193]:
# 3-Calculate the number of years since approval
df["years_since_approval"] = (
    (df["receive_date"] - df["fda_first_approval_date"]).dt.days / 365.25
).astype(int)
df["years_since_approval"].unique()

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7, -5, -4, -6,  8,  9, 10,
       11, 12, 13])

In [194]:
# To investegate which drug have report before thier approval date

df[df["years_since_approval"] < 0][
    ["generic_name", "fda_first_approval_date", "receive_date", "years_since_approval"]
].drop_duplicates().sort_values("years_since_approval")

      generic_name fda_first_approval_date receive_date  years_since_approval
57673  tirzepatide              2022-05-13   2015-07-28                    -6
45825  tirzepatide              2022-05-13   2016-09-28                    -5
45821  tirzepatide              2022-05-13   2016-08-31                    -5
45828  tirzepatide              2022-05-13   2016-10-17                    -5
45818  tirzepatide              2022-05-13   2016-06-30                    -5
...            ...                     ...          ...                   ...
46742  tirzepatide              2022-05-13   2021-04-26                    -1
46737  tirzepatide              2022-05-13   2021-04-20                    -1
57781  tirzepatide              2022-05-13   2020-12-29                    -1
57784  tirzepatide              2022-05-13   2021-02-04                    -1
57797  tirzepatide              2022-05-13   2021-03-11                    -1

[94 rows x 4 columns]

In [195]:
df.loc[
    df["years_since_approval"] < 0,
    "generic_name"
].value_counts()

generic_name
tirzepatide    1123
semaglutide     369
Name: count, dtype: int64

In [208]:
# 4-Assign severity levels based on the "serious_outcome" column
# 0 = No specified serious outcome
# 1 = Disabling
# 2 = Hospitalization
# 3 = Life-threatening
# 4 = Death

def get_severity(row):
    if row["seriousness_death"] == True:
        return 4
    elif row["seriousness_lifethreatening"] == True:
        return 3
    elif row["seriousness_hospitalization"] == True:
        return 2
    elif row["seriousness_disabling"] == True:
        return 1
    else:
        return 0

df["severity_level"] = df.apply(get_severity, axis=1)

In [197]:
# get the severety of each report

df_severity = (
    df.groupby("safetyreportid", as_index=False)["severity_level"]
      .max())
df_severity

       safetyreportid  severity_level
0            10005908               2
1            10006249               4
2            10006256               0
3            10006258               4
4            10006261               4
...               ...             ...
54165        24848430               0
54166        24852275               0
54167        24853716               0
54168        24853808               1
54169        24857834               0

[54170 rows x 2 columns]

In [198]:
df.head(5)

,safetyreportid,generic_name,brand_queried,receive_date,country,serious,seriousness_death,seriousness_lifethreatening,seriousness_hospitalization,seriousness_disabling,patient_age,patient_age_unit,patient_sex,reaction,reaction_outcome,brand_names,manufacturer,indication,fda_first_approval_date,drug_class,approval_year,years_since_approval,severity_level
0,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,Stenosis,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,GLP-1 receptor agonist,2017,-3,2
1,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,Hunger,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,GLP-1 receptor agonist,2017,-3,2
2,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,Visual impairment,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,GLP-1 receptor agonist,2017,-3,2
3,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,Incorrect dose administered,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,GLP-1 receptor agonist,2017,-3,2
4,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,Inappropriate schedule of product administration,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,GLP-1 receptor agonist,2017,-3,2

In [206]:
df_reports = (
    df_age
    .merge(df_gender, on="safetyreportid", how="outer")
    .merge(df_severity, on="safetyreportid", how="outer"))
df_reports

       safetyreportid  patient_age patient_sex  severity_level
0            10005908         52.0      Female               2
1            10006249         66.0        Male               4
2            10006256         84.0      Female               0
3            10006258          NaN        Male               4
4            10006261         71.0        Male               4
...               ...          ...         ...             ...
54165        24848430          NaN         NaN               0
54166        24852275         51.0      Female               0
54167        24853716         70.0        Male               0
54168        24853808         53.0      Female               1
54169        24857834          NaN         NaN               0

[54170 rows x 4 columns]

In [204]:
df_reports = df_reports.dropna(
    subset=["patient_sex"]
).copy()

In [205]:
df_reports.isna().mean().round(4) * 100

safetyreportid     0.00
patient_age       40.06
patient_sex        0.00
severity_level     0.00
dtype: float64

## step 4 : EDA/ Data analysis

In [207]:
## Analysis 1 — Severity distribution

severity_counts = (
    df_reports["severity_level"]
    .value_counts()
    .sort_index()
)

severity_counts

severity_level
0    46625
1      374
2     5314
3      564
4     1293
Name: count, dtype: int64

In [216]:
# Severity distribution percentage
severity_percentage = round(((
    df_reports["severity_level"]
    .value_counts(normalize=True)
    .sort_index())*100),2)

severity_percentage

severity_level
0    86.07
1     0.69
2     9.81
3     1.04
4     2.39
Name: proportion, dtype: float64

In [215]:
# Create a mapping of severity levels to their corresponding labels
severity_labels = {
    0: "No specified serious outcome",
    1: "Disabling",
    2: "Hospitalization",
    3: "Life-threatening",
    4: "Death"
}

df_reports["severity_label"] = df_reports["severity_level"].map(severity_labels)

In [228]:
severity_plot = (df_reports["severity_label"].value_counts().reset_index())

severity_plot.columns = ["severity", "number_of_reports"]

fig = px.bar(
    severity_plot,
    x="number_of_reports",
    y="severity",
    text="number_of_reports",
    title="Distribution of Adverse-Event Severity",
    labels={
        "severity": "Severity",
        "number_of_reports": "Number of Safety Reports"})
fig.show()

In [229]:
fig = px.pie(
    df_reports,
    names="severity_label",
    title="Distribution of Adverse-Event Severity")
fig.show()

In [231]:
# Analysis 2 — Severity distribution by age
px.box(
    df_reports,
    x="severity_label",
    y="patient_age")

In [239]:
# Analysis 3 — Severity distribution by age and sex
age_sex_severity = (
    df_reports
    .groupby(["severity_label", "patient_sex"])["patient_age"]
    .mean()
    .reset_index())

In [238]:
fig = px.bar(
    age_sex_severity,
    x="severity_label",
    y="patient_age",
    color="patient_sex",
    barmode="group",
    title="Mean Patient Age by Sex and Severity Level",
    labels={
        "severity_label": "Severity Level",
        "patient_age": "Mean Patient Age (years)",
        "patient_sex": "Sex"
    }
)

fig.show()

In [283]:
# Analysis 4 — Does the distribution of adverse-event severity differ among GLP-1 drugs?

df[["generic_name", "brand_queried"]].drop_duplicates().sort_values("generic_name")

        generic_name brand_queried
136373   albiglutide       TANZEUM
94121    dulaglutide     TRULICITY
106035     exenatide        BYETTA
123418     exenatide      BYDUREON
67674    liraglutide       VICTOZA
81021    liraglutide       SAXENDA
136316  lixisenatide       ADLYXIN
0        semaglutide       OZEMPIC
16530    semaglutide        WEGOVY
30985    semaglutide      RYBELSUS
45818    tirzepatide      MOUNJARO
57673    tirzepatide      ZEPBOUND

In [284]:
df_brand = (
    df[["safetyreportid", "brand_queried"]]
    .drop_duplicates(subset="safetyreportid")
)

In [ ]:
df_reports = df_reports.merge(
    df_brand,
    on="safetyreportid",
    how="left")

In [288]:
severity_order = [
    "No specified serious outcome",
    "Disabling",
    "Hospitalization",
    "Life-threatening",
    "Death"]

fig = px.bar(
    brand_severity,
    x="brand_queried",
    y="count",
    facet_row="severity_label",
    text="count",
    category_orders={
        "severity_label": [
            "Death",
            "Life-threatening",
            "Hospitalization",
            "Disabling",
            "No specified serious outcome"
        ]
    },
    title="Adverse-Event Severity by GLP-1 Brand",
    labels={
        "brand_queried": "Brand",
        "count": "Number of Reports"
    }
)

# Each severity chart gets its own Y-axis scale
fig.update_yaxes(
    matches=None
)

# Show brand names on every chart
fig.update_xaxes(
    showticklabels=True,
    tickangle=-45
)

# Show counts above bars
fig.update_traces(
    textposition="outside"
)

# Make the full figure large enough to read
fig.update_layout(
    height=1400,
    width=1100,
    showlegend=False
)

# Clean subplot titles
fig.for_each_annotation(
    lambda a: a.update(
        text=a.text.replace("severity_label=", "")
    )
)

fig.show()

In [ ]:
# Analysis 5 — Geographical Distribution of top 5 GLP-1 Adverse-Event Reports.

country_reports = (
    df[["safetyreportid", "country"]]
    .drop_duplicates()
)
country_report_table = (
    country_reports
    .groupby("country")["safetyreportid"]
    .count()
    .reset_index(name="report_count")
    .sort_values("report_count", ascending=False)
    .reset_index(drop=True)).head(5)
country_report_table

  country  report_count
0      US         47414
1     UNK          1844
2      GB           772
3      JP           711
4      CA           431

In [303]:
fig = px.pie(
    country_report_table,
    names="country",
    values="report_count",
    title="Distribution of GLP-1 Adverse-Event Reports by Country"
)

fig.show()

In [314]:
# Analysis 6: Timeline of FDA Approval for GLP-1 Drugs

approval_table = (
    df[
        [
            "brand_queried",
            "manufacturer",
            "approval_year"
        ]
    ]
    .drop_duplicates()
    .sort_values("approval_year")
    .reset_index(drop=True)
)

approval_table

   brand_queried  manufacturer  approval_year
0       BYDUREON   AstraZeneca           2005
1         BYETTA   AstraZeneca           2005
2        SAXENDA  Novo Nordisk           2010
3        VICTOZA  Novo Nordisk           2010
4      TRULICITY     Eli Lilly           2014
5        TANZEUM           GSK           2014
6        ADLYXIN        Sanofi           2016
7        OZEMPIC  Novo Nordisk           2017
8       RYBELSUS  Novo Nordisk           2017
9         WEGOVY  Novo Nordisk           2017
10      ZEPBOUND     Eli Lilly           2022
11      MOUNJARO     Eli Lilly           2022

In [317]:
fig = px.line(
    approval_table,
    x="approval_year",
    y="brand_queried",
    markers=True,
    hover_data=[
            "manufacturer"
        ],
    title="Timeline of FDA Approval for GLP-1 Drugs",
    labels={
        "approval_year": "FDA Approval Year",
        "brand_queried": "Brand Name",
        "manufacturer": "Manufacturer"
    }
)

fig.show()

## Extra tables

In [305]:
drug_table = (
    df[["brand_queried", "generic_name", "manufacturer"]]
    .drop_duplicates()
    .sort_values(["manufacturer", "brand_queried"])
    .reset_index(drop=True)
)

drug_table

   brand_queried  generic_name  manufacturer
0       BYDUREON     exenatide   AstraZeneca
1         BYETTA     exenatide   AstraZeneca
2       MOUNJARO   tirzepatide     Eli Lilly
3      TRULICITY   dulaglutide     Eli Lilly
4       ZEPBOUND   tirzepatide     Eli Lilly
5        TANZEUM   albiglutide           GSK
6        OZEMPIC   semaglutide  Novo Nordisk
7       RYBELSUS   semaglutide  Novo Nordisk
8        SAXENDA   liraglutide  Novo Nordisk
9        VICTOZA   liraglutide  Novo Nordisk
10        WEGOVY   semaglutide  Novo Nordisk
11       ADLYXIN  lixisenatide        Sanofi

In [304]:
indication_table = (
    df[["brand_queried", "generic_name", "indication"]]
    .drop_duplicates()
    .sort_values("brand_queried")
    .reset_index(drop=True)
)

indication_table

   brand_queried  generic_name               indication
0        ADLYXIN  lixisenatide          type-2-diabetes
1       BYDUREON     exenatide          type-2-diabetes
2         BYETTA     exenatide          type-2-diabetes
3       MOUNJARO   tirzepatide  type-2-diabetes/obesity
4        OZEMPIC   semaglutide  type-2-diabetes/obesity
5       RYBELSUS   semaglutide  type-2-diabetes/obesity
6        SAXENDA   liraglutide  type-2-diabetes/obesity
7        TANZEUM   albiglutide          type-2-diabetes
8      TRULICITY   dulaglutide          type-2-diabetes
9        VICTOZA   liraglutide  type-2-diabetes/obesity
10        WEGOVY   semaglutide  type-2-diabetes/obesity
11      ZEPBOUND   tirzepatide  type-2-diabetes/obesity

In [307]:
reaction_table = (
    df.groupby("reaction")["safetyreportid"]
    .count()
    .reset_index(name="report_count")
    .sort_values("report_count", ascending=False)
    .reset_index(drop=True)
)

reaction_table.head(10)

                      reaction  report_count
0                       Nausea          7629
1                     Vomiting          3661
2      Blood glucose increased          3373
3                    Diarrhoea          3156
4  Incorrect dose administered          3068
5          Injection site pain          2984
6             Device use error          2722
7             Weight decreased          2556
8                Off label use          2450
9           Decreased appetite          2065